### ISSUE TITLE
volume flyout triggering when you open the app

### ISSUE THREAD

**Issue by legofanlovessayori** [Far-Se/tabame#2]
**Describe the bug:**
basicly the new windows 11 volume flyout gets triggered for about 5 to 6 times when you open the app
**Screenshots: (optional)**
https://user-images.githubusercontent.com/94994630/187025439-b12b690a-c36d-4b5b-b6b5-951903f57b8f.mp4
**Desktop:**
 - Windows Version: Windows 11 build 25188.1000
 - Tabame Version: 1.0.0

**Comment by Far-Se** [comment]
Thanks for reporting. I've fixed it now. Tabame has a feature to change flyouts but works on Windows 10 only, didn't knew Windows 11 has different flyouts.

I will release an update around 8 PM CET today.

If you find any other issue please report them 😄 

![image](https://user-images.githubusercontent.com/20853986/187028232-47abad4a-d2f1-4493-877d-d87e7bb20af8.png)

**Comment by legofanlovessayori** [comment]
11 had the 10 volume flyouts in 22000.x builds (aka the october 2021 release), nickel redesigned them to fit inline with the rest
