### ISSUE TITLE
Grid doesn't have to be all the same size

### ISSUE THREAD

**Issue by damywise** [Far-Se/tabame#4]
I have a monitor with the resolution 3440 x 1440
That would be (1920 + 1520) x (1080 + 360)
Which means if I want a window to be 1920 x 1080, the width needs to be set to the GCD of 1920 and 3440, which is 80 as of now.
I think it would be nice to have at least one selection area that has different size.
Or any other solution that would solve my problem (Except using other apps).
This could also enable `double`s instead of just `int`s in my opinion

**Comment by Far-Se** [comment]
Hi, sorry for delayed response, I've made a feature called "Predefines Sizes" in the same you posted this but then I started working on other features and forgot to respond.

Windows window size accepts only `int`, so it will pointless to make it double.

But I made this:

![image](https://user-images.githubusercontent.com/20853986/197335657-556d6faf-4345-42b1-9a50-999c075c5c92.png)


![image](https://user-images.githubusercontent.com/20853986/197331160-c1532110-50b2-4dee-ae24-2bfc3f0a9d64.png)

You can set specific sizes and set them from QuickMenu when you need a window to have a specific size.

I will release v1.2 today or tomorrow, have Auto Update on or try tomorrow.
