### ISSUE TITLE
Typo in First Run Settings

### ISSUE THREAD

**Issue by Panagiotis-Zachos** [Far-Se/tabame#5]
There is a typo at the bottom of the First Run Settings Page, it says "... features **then one** listed above!", I think it should say "features than **the ones** listed above!"

![image](https://user-images.githubusercontent.com/31392984/201298133-01f4a4a8-f1d2-4e31-90c9-507daefceec3.png)

**Comment by Far-Se** [comment]
Thanks, I've fixed it!
