### ISSUE TITLE
Windows Taskbar

### ISSUE THREAD

**Issue by michal-stefaniak** [Far-Se/tabame#6]
when my pc launched i pressed no on tabame admin request and now im stuck with no taskbar please help im a stundent and i need to use my pc for schoolwork

**Comment by Far-Se** [comment]
Can you open Tabame? Press the hotkey you set on the bottom of the screen and the taskbar will appear. Or there is a button on QuickMenu to toggle it.
If Tabame does not start, press WinKey on pc and type "tabame" and open it again, or find it on `%localappdata%\Tabame`.
Or you can restart your PC and you will get your taskbar back. Right click the taskbar and press "Lock all taskbars"

**Comment by michal-stefaniak** [comment]
i fixed the overall problem of no taskbar its just stuck in hied in desktop view mode and i dont have activated windows to change that, i tried changing registry but it didnt work+ after my taskbar didnt work i decided to delete tabame to see if it would fix
